# Generated by Django 5.2.13 on 2026-04-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auditlog_table_name_auditlog_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('insert', 'Insert'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login')], max_length=50),
        ),
    ]
