# Generated by Django 5.2.13 on 2026-04-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_auditlog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='table_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
