# Generated by Django 6.0.3 on 2026-03-26 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualFatigueAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('attention_score', models.FloatField(default=0.0)),
                ('fatigue_score', models.FloatField(default=0.0)),
                ('yawn_count', models.PositiveIntegerField(default=0)),
                ('eyes_closed_secs', models.FloatField(default=0.0)),
                ('result_label', models.CharField(blank=True, choices=[('atento', 'Atento'), ('fatigado', 'Fatigado'), ('distraido', 'Distraido')], max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fatigue_individual_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FatigueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('attention_score', models.FloatField(default=0.0)),
                ('fatigue_score', models.FloatField(default=0.0)),
                ('yawn_count', models.PositiveIntegerField(default=0)),
                ('eyes_closed_secs', models.FloatField(default=0.0)),
                ('result_label', models.CharField(blank=True, choices=[('atento', 'Atento'), ('fatigado', 'Fatigado'), ('distraido', 'Distraido')], max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatigue_records', to='classrooms.student')),
            ],
            options={
                'db_table': 'fatigue_record',
            },
        ),
        migrations.CreateModel(
            name='FatigueSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatigue_sessions', to='classrooms.classroom')),
            ],
            options={
                'db_table': 'fatigue_session',
                'ordering': ['-created_at'],
            },
        ),
    ]
