# Generated by Django 6.0.3 on 2026-03-26 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0002_initial'),
        ('fatigue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fatiguesession',
            name='maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatigue_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fatiguerecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='fatigue.fatiguesession'),
        ),
        migrations.AddField(
            model_name='individualfatigueanalysis',
            name='maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_fatigue_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualfatigueanalysis',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatigue_analyses', to='classrooms.student'),
        ),
        migrations.AddIndex(
            model_name='fatiguesession',
            index=models.Index(fields=['classroom', 'date'], name='fatigue_ses_classro_f982d0_idx'),
        ),
        migrations.AddIndex(
            model_name='fatiguesession',
            index=models.Index(fields=['maestro', 'status'], name='fatigue_ses_maestro_2a1d6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fatiguerecord',
            unique_together={('session', 'student')},
        ),
        migrations.AddIndex(
            model_name='individualfatigueanalysis',
            index=models.Index(fields=['student', 'date'], name='fatigue_ind_student_ce32a0_idx'),
        ),
        migrations.AddIndex(
            model_name='individualfatigueanalysis',
            index=models.Index(fields=['maestro', 'status'], name='fatigue_ind_maestro_252395_idx'),
        ),
    ]
